baseURL = "/"
languageCode = "en-us"
title = "K-5"
theme = "ink"
paginate = 5



pygmentsstyle = "vs"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-123-45"
disqusShortname = "ink-demo"

[params]
	subtitle = "[Our life is our own, and Our future is up to us](https://195.2.81.61/movie/enola-holmes-2020/)"

	# Optional 64x64 avatar image.
	avatar = "https://image.flaticon.com/icons/png/512/1185/1185005.png"

	# Content types to disable Disqus on.
	disableDisqusTypes = ["page"]
	
	featherIconsCDN = true

	mode = "auto" # "dark" or "auto"
	# customCSS = "css/custom.css"  # Custom CSS applied to default styles.
	# customDarkCSS = "css/custom-dark.css"  # Custom styles applied to dark mode css.
	# customJS = ["js/custom.js", "js/custom1.js"]  # Custom JS scripts.

# Nav.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://www.instagram.com/k.inovasi05/"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/K533486495"


[taxonomies]
   tag = "tags"
